
import java.awt.Color;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author juani
 */
public class GraficadorDeBarras extends javax.swing.JPanel {

    /**
     * Creates new form GraficadorDeBarras
     */
    private String vector1 = "TituloX1,TituloX2,TituloX3";
    private String vector2 = "TituloY1,TituloY2,TituloY3";
    private String vector3 = "50,100,150";
    private String ve1[]=vector1.split(",");
    private String ve2[]=vector2.split(",");
    private String ve3[]=vector3.split(",");
    public GraficadorDeBarras() {
        initComponents();
        ActualizarGrafico(ve1,ve2,ve3);
    }
    public void ActualizarGrafico(String v1[],String v2[], String v3[]){
        
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        dataset.setValue(Integer.parseInt(v3[0]), v1[0]+"", v2[0]+"");
        dataset.setValue(Integer.parseInt(v3[1]), v1[0]+"", v2[1]+"");
        dataset.setValue(Integer.parseInt(v3[2]), v1[0]+"", v2[2]+"");
        
        JFreeChart chart = ChartFactory.createBarChart3D("Grafica de barras","Titulos",v1[0]+"",dataset,PlotOrientation.VERTICAL,false,true,false);
        CategoryPlot p=chart.getCategoryPlot();
        p.setRangeGridlinePaint(Color.black);
        //ChartFrame frame = new ChartFrame("Grafica de barras", chart);
        //frame.setVisible(true);
        //frame.setSize(450,350);
        ChartPanel chartPanel = new ChartPanel(chart);
        jPanel1.removeAll();
        jPanel1.add(chartPanel);
        jPanel1.updateUI();
        //frame.setLocationRelativeTo(null);
    }
    public void setVector1(String c){
        ve1=c.split(",");
        vector1=ve1[0]+","+ve1[1]+","+ve1[2];
        ActualizarGrafico(ve1,ve2,ve3);
    }
    public String getVector1(){
        return vector1;
    }
    public void setVector2(String c){
        ve2=c.split(",");
        vector2=ve2[0]+","+ve2[1]+","+ve2[2];
        ActualizarGrafico(ve1,ve2,ve3);
    }
    public String getVector2(){
        return vector2;
    }
    public void setVector3(String c){
        ve3=c.split(",");
        vector3=ve3[0]+","+ve3[1]+","+ve3[2];
        ActualizarGrafico(ve1,ve2,ve3);
    }
    public String getVector3(){
        return vector3;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
